### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/MuladdMacro.jl#16]
@JuliaRegistrator register()

**Comment by devmotion** [comment]
The version number was already updated in the PR, and hence version 0.2.2 would be skipped. Therefore the PR to the registry is not merge automatically: https://github.com/JuliaRegistries/General/pull/8033#issuecomment-575140867

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
