### ISSUE TITLE
Multiply-add with minus signs doesn't get converted to muladd

### ISSUE THREAD

**Issue by ikirill** [JuliaDiffEq/MuladdMacro.jl#5]
I expected this to work, but it didn't. There is generally no problem with having minus signs inside muladd, because FMA instructions allow for that, so expressions like `b-a*x` should be converted to `muladd(-a, x, b)`.

```
julia> macroexpand(:(MuladdMacro.@muladd b - a * x))
:(b - a * x)

julia> macroexpand(:(MuladdMacro.@muladd b + a * x))
:((muladd)(a, x, b))
```

**Comment by ChrisRackauckas** [comment]
Yeah, it looks like we're missing this. We're looking directly for `+`s and handling that. I'm not sure the easiest way to implement this.
