### ISSUE TITLE
use `if` instead of MacroTools

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaDiffEq/MuladdMacro.jl#9]
MacroTools' pattern matching is very slow, mostly due to using exceptions to signal no-match. This causes https://github.com/JuliaLang/julia/issues/28221. Ideally MacroTools can be fixed too, but in the meantime it seems easier to switch this package to use simple tests like `isexpr(ex, :call) && ex.args[1] == :+` instead of MacroTools. Of course that can be abstracted into `iscall(ex, :+)`, etc. --- feel free to go nuts with that.

**Comment by ChrisRackauckas** [comment]
That was just added by https://github.com/JuliaDiffEq/MuladdMacro.jl/pull/7 . We can revert the MacroTools changes as suggested. @devmotion ?

**Comment by YingboMa** [comment]
Can I give this issue a try?

**Comment by ChrisRackauckas** [comment]
Yes

**Comment by devmotion** [comment]
Yes seems like we should replace all occurrences of `@capture` that were added there. In my opinion the changes nevertheless were helpful to simplify the overall logic of MuladdMacro and added the subtraction handling, so I think we shouldn't just revert everything?

**Comment by MikeInnes** [comment]
Yes, all the utility functions like `postwalk` are fine, it's only calling `@capture` recursively that exposes this issue. It looks like the patterns are simple enough that explicit tests won't be a serious readability sacrifice.

**Comment by YingboMa** [comment]
Closed by #11

**Comment by MikeInnes** [comment]
FYI there's a fix for this in this PR – https://github.com/MikeInnes/MacroTools.jl/pull/104

Would be nice to hear if you see an improvement in this case.
